[supabase]
SUPABASE_URL = "https://xtmfmfkpgommfdujhvev.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0bWZtZmtwZ29tbWZkdWpodmV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYxODI3ODYsImV4cCI6MjA0MTc1ODc4Nn0.pr8ljk1mh8bPqjDLhnRKXDNeNxNdnewBz79oufQCrDk"

[authentication]
password = "p1"